### ISSUE TITLE
Validation Hangs

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/spark-modeler#322] opened 2019-04-10 15:37 UTC
Changing the Identifier/"ProcessId" to numbers throws a 422 (Unprocessable Entity) error, and the user cannot make any further changes to the Process because it will no longer save. Even changing the Identifier back to "ProcessId" does not allow it to save. 

1. Create New Process
1. Change Process Identifier from "ProcessId" to any string of numbers
1. Press save twice

**Comment by tuantruong625** [comment] 2019-04-10 17:59
Duplicate of #323

**Closed by tuantruong625** 2019-04-10 17:59 UTC
Labels: bug
